package generator

import (
	"fmt"
	"io"
	"regexp"
	"strings"
	"time"

	"github.com/0xKirisame/shinkai-shoujo/internal/correlation"
)

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// TerraformGenerator produces Terraform HCL output for least-privilege policies.
type TerraformGenerator struct{}

// Generate writes Terraform HCL to w, one resource per IAM role.
func (g *TerraformGenerator) Generate(results []correlation.Result, w io.Writer) error {
	fmt.Fprintf(w, "# Generated by shinkai-shoujo on %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(w, "# Review carefully before applying — NEVER auto-apply.\n\n")

	for _, r := range results {
		name := terraformResourceName(r.IAMRole)
		fmt.Fprintf(w, "# Role: %s\n", r.IAMRole)
		fmt.Fprintf(w, "# Risk level of unused privileges: %s\n", r.RiskLevel)
		fmt.Fprintf(w, "# Assigned: %d | Used: %d | Unused: %d\n",
			len(r.Assigned), len(r.Used), len(r.Unused))

		switch {
		case len(r.Unused) == 0:
			// All assigned privileges were observed — no changes needed.
			fmt.Fprintf(w, "# No unused privileges detected for this role.\n\n")
			continue

		case len(r.Used) == 0:
			// Role has assigned privileges but was never observed making any call
			// within the observation window. A policy with an empty Action list is
			// invalid; manual review is required before removing privileges.
			fmt.Fprintf(w, "# WARNING: Role has %d assigned privilege(s) but made no observed\n", len(r.Assigned))
			fmt.Fprintf(w, "# calls in the observation window. Verify the window is long enough\n")
			fmt.Fprintf(w, "# before removing privileges. No policy block generated.\n\n")
			continue
		}

		fmt.Fprintf(w, `resource "aws_iam_policy" "%s_least_privilege" {`+"\n", name)
		fmt.Fprintf(w, `  name        = "%s-least-privilege"`+"\n", name)
		fmt.Fprintf(w, `  description = "Least-privilege policy for %s (shinkai-shoujo generated)"`+"\n", r.IAMRole)
		fmt.Fprintf(w, "  policy = jsonencode({\n")
		fmt.Fprintf(w, "    Version = \"2012-10-17\"\n")
		fmt.Fprintf(w, "    Statement = [{\n")
		fmt.Fprintf(w, "      Effect = \"Allow\"\n")
		fmt.Fprintf(w, "      Action = [\n")

		for _, p := range r.Used {
			fmt.Fprintf(w, "        %q,\n", p)
		}

		fmt.Fprintf(w, "      ]\n")
		fmt.Fprintf(w, "      Resource = \"*\"\n")
		fmt.Fprintf(w, "    }]\n")
		fmt.Fprintf(w, "  })\n")
		fmt.Fprintf(w, "}\n\n")
	}

	totalUnused := 0
	for _, r := range results {
		totalUnused += len(r.Unused)
	}
	fmt.Fprintf(w, "# Summary: %d roles analyzed, %d total unused privileges found.\n", len(results), totalUnused)

	return nil
}

// terraformResourceName converts an IAM role ARN or name to a valid Terraform resource name.
func terraformResourceName(roleARN string) string {
	lower := strings.ToLower(roleARN)
	safe := nonAlnum.ReplaceAllString(lower, "_")
	safe = strings.Trim(safe, "_")
	if safe == "" {
		safe = "role"
	}
	return safe
}
